export const CURIOSITIES: string[] = [
  'O Brasil é a única seleção que participou de todas as 23 edições da Copa do Mundo.',
  'O Brasil é o maior campeão da história, com 5 títulos: 1958, 1962, 1970, 1994 e 2002.',
  'O Brasil é o único país pentacampeão do mundo.',
  'Jairzinho é o único jogador a marcar gol em todos os jogos de uma edição de Copa (1970, pelo Brasil).',
  'O Brasil detém o recorde de seleção que mais marcou gols na história das Copas: 237 gols em 22 edições (média de 10 por Mundial).',
  'Em 1950, o Brasil sediou a Copa e perdeu a final para o Uruguai no Maracanã, no episódio conhecido como "Maracanazo".',
  'O público da final de 1950 no Maracanã foi de mais de 199 mil pessoas - o maior já registrado em um jogo de futebol.',
  'O Brasil foi sede de Copa do Mundo duas vezes: 1950 e 2014.',
  'O Brasil foi vice-campeão em 1950 e na decisão de pênaltis de 1998 contra a França.',
  'Cafu é o único jogador da história a disputar três finais de Copa consecutivas: 1994, 1998 e 2002.',
  'Cafu disputou 20 partidas de Copa do Mundo pelo Brasil - mais que qualquer outro jogador brasileiro.',
  'Em 1994, o Brasil venceu a Itália nos pênaltis e conquistou o tetracampeonato nos Estados Unidos.',
  'Em 2002, o Brasil venceu a Alemanha por 2x0 na final, com dois gols de Ronaldo, e conquistou o pentacampeonato.',
  'O Brasil foi campeão em 1958 e 1962 de forma consecutiva.',
  'Ronaldo Nazário é o maior artilheiro brasileiro em Copas do Mundo, com 15 gols.',
  'O Brasil foi eliminado ainda na fase de grupos em 1966, com apenas uma vitória em três jogos.',
  'Em 1986, o Brasil foi eliminado nas quartas de final, nos pênaltis.',
  'Miroslav Klose, da Alemanha, é um dos maiores artilheiros da história das Copas, com 16 gols em quatro edições (2002, 2006, 2010, 2014).',
  'Just Fontaine, da França, marcou 13 gols em uma única edição (1958) - recorde de gols em uma só Copa, até hoje imbatido.',
  'Gerd Müller, da Alemanha Ocidental, marcou 14 gols em apenas duas edições (1970 e 1974).',
  'O russo Oleg Salenko é o maior artilheiro de uma única partida de Copa: 5 gols, contra Camarões, em 1994.',
  'Roger Milla, de Camarões, é o jogador mais velho a marcar um gol em Copas: 42 anos, em 1994.',
  'O goleiro egípcio Essam El Hadary se tornou o atleta mais velho a disputar uma partida de Copa, com 45 anos e 161 dias, em 2018.',
  'Norman Whiteside, da Irlanda do Norte, é o jogador mais jovem a debutar em Copas: 17 anos e 41 dias, em 1982.',
  'Lothar Matthäus, da Alemanha, disputou 25 partidas em Copas do Mundo - um dos maiores recordes de participação em jogos.',
  'O gol mais rápido da história das Copas foi marcado por Hakan Şükür, da Turquia, contra a Coreia do Sul em 2002 (cerca de 11 segundos após o início).',
  'A maior goleada da história das Copas foi Hungria 10x1 sobre El Salvador, na fase de grupos de 1982.',
  'A derrota do Brasil por 7x1 para a Alemanha, em 2014, não é a maior goleada da história das Copas - perde para o 10x1 de 1982.',
  'A Copa de 1978 teve a maior proporção de jogos 0x0 da história: quase 16% das partidas.',
  'A Copa de 2010 teve o maior número de jogos decididos por diferença mínima de gols: 31 partidas.',
  'A partida entre Portugal e Holanda em 2006 ficou conhecida como "A Batalha de Nuremberg": 16 cartões amarelos e 4 vermelhos em um só jogo.',
  'A primeira Copa do Mundo, em 1930, teve apenas 13 seleções, após desistências por dificuldade de viagem até o Uruguai.',
  'O primeiro gol da história das Copas foi marcado pelo francês Lucien Laurent, em 1930.',
  'A Copa de 1950 foi a única edição que não teve uma final disputada em mata-mata - foi decidida em quadrangular.',
  'Antes da Copa de 1966, a taça Jules Rimet foi roubada durante uma exposição e encontrada dias depois por um cachorro chamado Pickles.',
  'A Copa de 1938 teve apenas 15 equipes, porque a Áustria foi anexada pela Alemanha após a qualificação.',
  'A Copa de 1994, nos EUA, teve a maior média de público da história até então: quase 69 mil pessoas por jogo.',
  'A Copa de 2002 foi a primeira disputada em dois países-sede ao mesmo tempo (Coreia do Sul e Japão) e a primeira fora da Europa e das Américas.',
  'A Copa de 1998 foi a primeira com 32 seleções na fase final.',
  'A Tunísia foi a primeira seleção africana a vencer uma partida de Copa do Mundo.',
  'A Copa de 2006 marcou a estreia do Togo - e por um erro no cerimonial, tocaram o hino errado antes do jogo contra a Coreia do Sul.',
  'A Alemanha é a seleção que mais vezes disputou finais de Copa: 8 vezes.',
  'O confronto que mais vezes ocorreu em finais de Copa foi Argentina x Alemanha: 1986, 1990 e 2014.',
  'Apenas seleções da Europa e da América do Sul já venceram uma Copa do Mundo.',
  'A Escócia disputou 8 Copas e nunca passou da fase de grupos em nenhuma delas.',
  'A Irlanda avançou da primeira fase em todas as 3 Copas que disputou: 1990, 1994 e 2002.',
  'El Salvador e Haiti são as únicas seleções a disputarem mais de uma Copa e perderem todos os jogos.',
  'A Hungria de 1954 venceu seus dois primeiros jogos da fase de grupos por 9x0 e 8x3, mas perdeu a final.',
  'Camarões (1982), Bélgica (1998) e Nova Zelândia (2010) foram eliminadas da fase de grupos de forma invicta, somando 3 empates cada.',
  'O Uruguai foi campeão em 1930 e nem participou da edição seguinte, em 1934.',
  'A Itália e o México estão entre as seleções com mais participações em Copas, com 18 edições.',
  'Chile (1930), Iugoslávia (1950) e Argélia (1982) tiveram o melhor desempenho de uma seleção eliminada na fase de grupos: 2 vitórias e 1 derrota.',
  'Antes de 1982, apenas 4 seleções de fora da Europa/América do Sul avançaram à fase final: EUA (1930), Cuba (1938), Coreia do Norte (1966) e México (1970).',
  'O Estádio Azteca, na Cidade do México, é o primeiro do mundo a receber três Copas: 1970, 1986 e 2026.',
  'O estádio com a maior altitude a já receber um jogo de Copa foi o Nemesio Díez, no México, a 2.670 metros de altitude.',
  'México, Brasil, França, Itália, Alemanha e Estados Unidos são os únicos países que já sediaram a Copa duas vezes (o México será o primeiro a sediar três, em 2026).',
  'A Copa de 2026 é a primeira da história com 48 seleções, divididas em 12 grupos de 4 times.',
  'Cabo Verde, Curaçao, Jordânia e Uzbequistão fazem sua primeira aparição em Copas do Mundo em 2026.',
  'O formato de 2026 criou uma nova fase eliminatória, chamada oficialmente de "Round of 32", antes das oitavas de final.',
  'Nenhum estádio foi construído especificamente para a Copa de 2026 - todos os 16 já existiam e foram adaptados.',
  'A Copa de 2026 é a primeira disputada por três países-sede ao mesmo tempo: Estados Unidos, México e Canadá.',
];
