export const CURIOSITIES: string[] = [
  'O Brasil é a única seleção que participou de todas as 23 edições da Copa do Mundo.',
  'O Brasil é o maior campeão da história, com 5 títulos: 1958, 1962, 1970, 1994 e 2002.',
  'O Brasil é o único país pentacampeão do mundo.',
  'Jairzinho é o único jogador a marcar gol em todos os jogos de uma edição de Copa (1970, pelo Brasil).',
  'O Brasil detém o recorde de seleção que mais marcou gols na história das Copas: 237 gols em 22 edições (média de 10 por Mundial).',
  'Em 1950, o Brasil sediou a Copa e perdeu a final para o Uruguai no Maracanã, no episódio conhecido como "Maracanazo".',
  'O público da final de 1950 no Maracanã foi de mais de 199 mil pessoas — o maior já registrado em um jogo de futebol.',
  'O Brasil foi sede de Copa do Mundo duas vezes: 1950 e 2014.',
  'O Brasil foi vice-campeão em 1950 e na decisão de pênaltis de 1998 contra a França.',
  'Cafu é o único jogador da história a disputar três finais de Copa consecutivas: 1994, 1998 e 2002.',
  'Cafu disputou 20 partidas de Copa do Mundo pelo Brasil — mais que qualquer outro jogador brasileiro.',
  'Em 1994, o Brasil venceu a Itália nos pênaltis e conquistou o tetracampeonato nos Estados Unidos.',
  'Em 2002, o Brasil venceu a Alemanha por 2x0 na final, com dois gols de Ronaldo, e conquistou o pentacampeonato.',
  'O Brasil foi campeão em 1958 e 1962 de forma consecutiva.',
  'Ronaldo Nazário é o maior artilheiro brasileiro em Copas do Mundo, com 15 gols.',
  'O Brasil foi eliminado ainda na fase de grupos em 1966, com apenas uma vitória em três jogos.',
  'Em 1986, o Brasil foi eliminado nas quartas de final, nos pênaltis.',
  'Miroslav Klose, da Alemanha, é um dos maiores artilheiros da história das Copas, com 16 gols em quatro edições (2002, 2006, 2010, 2014).',
  'Just Fontaine, da França, marcou 13 gols em uma única edição (1958) — recorde de gols em uma só Copa, até hoje imbatido.',
  'Gerd Müller, da Alemanha Ocidental, marcou 14 gols em apenas duas edições (1970 e 1974).',
  'O russo Oleg Salenko é o maior artilheiro de uma única partida de Copa: 5 gols, contra Camarões, em 1994.',
  'Roger Milla, de Camarões, é o jogador mais velho a marcar um gol em Copas: 42 anos, em 1994.',
  'O goleiro egípcio Essam El Hadary se tornou o atleta mais velho a disputar uma partida de Copa, com 45 anos e 161 dias, em 2018.',
  'Norman Whiteside, da Irlanda do Norte, é o jogador mais jovem a debutar em Copas: 17 anos e 41 dias, em 1982.',
  'Lothar Matthäus, da Alemanha, disputou 25 partidas em Copas do Mundo — um dos maiores recordes de participação em jogos.',
  'O gol mais rápido da história das Copas foi marcado por Hakan Şükür, da Turquia, contra a Coreia do Sul em 2002 (cerca de 11 segundos após o início).',
  'A maior goleada da história das Copas foi Hungria 10x1 sobre El Salvador, na fase de grupos de 1982.',
  'A derrota do Brasil por 7x1 para a Alemanha, em 2014, não é a maior goleada da história das Copas — perde para o 10x1 de 1982.',
  'A Copa de 1978 teve a maior proporção de jogos 0x0 da história: quase 16% das partidas.',
  'A Copa de 2010 teve o maior número de jogos decididos por diferença mínima de gols: 31 partidas.',
  'A partida entre Portugal e Holanda em 2006 ficou conhecida como "A Batalha de Nuremberg": 16 cartões amarelos e 4 vermelhos em um só jogo.',
  'A primeira Copa do Mundo, em 1930, teve apenas 13 seleções, após desistências por dificuldade de viagem até o Uruguai.',
  'O primeiro gol da história das Copas foi marcado pelo francês Lucien Laurent, em 1930.',
  'A Copa de 1950 foi a única edição que não teve uma final disputada em mata-mata — foi decidida em quadrangular.',
  'Antes da Copa de 1966, a taça Jules Rimet foi roubada durante uma exposição e encontrada dias depois por um cachorro chamado Pickles.',
  'A Copa de 1938 teve apenas 15 equipes, porque a Áustria foi anexada pela Alemanha após a qualificação.',
  'A Copa de 1994, nos EUA, teve a maior média de público da história até então: quase 69 mil pessoas por jogo.',
  'A Copa de 2002 foi a primeira disputada em dois países-sede ao mesmo tempo (Coreia do Sul e Japão) e a primeira fora da Europa e das Américas.',
  'A Copa de 1998 foi a primeira com 32 seleções na fase final.',
  'A Tunísia foi a primeira seleção africana a vencer uma partida de Copa do Mundo.',
  'A Copa de 2006 marcou a estreia do Togo — e por um erro no cerimonial, tocaram o hino errado antes do jogo contra a Coreia do Sul.',
  'A Alemanha é a seleção que mais vezes disputou finais de Copa: 8 vezes.',
  'O confronto que mais vezes ocorreu em finais de Copa foi Argentina x Alemanha: 1986, 1990 e 2014.',
  'Apenas seleções da Europa e da América do Sul já venceram uma Copa do Mundo.',
  'A Escócia disputou 8 Copas e nunca passou da fase de grupos em nenhuma delas.',
  'A Irlanda avançou da primeira fase em todas as 3 Copas que disputou: 1990, 1994 e 2002.',
  'El Salvador e Haiti são as únicas seleções a disputarem mais de uma Copa e perderem todos os jogos.',
  'A Hungria de 1954 venceu seus dois primeiros jogos da fase de grupos por 9x0 e 8x3, mas perdeu a final.',
  'Camarões (1982), Bélgica (1998) e Nova Zelândia (2010) foram eliminadas da fase de grupos de forma invicta, somando 3 empates cada.',
  'O Uruguai foi campeão em 1930 e nem participou da edição seguinte, em 1934.',
  'A Itália e o México estão entre as seleções com mais participações em Copas, com 18 edições.',
  'Chile (1930), Iugoslávia (1950) e Argélia (1982) tiveram o melhor desempenho de uma seleção eliminada na fase de grupos: 2 vitórias e 1 derrota.',
  'Antes de 1982, apenas 4 seleções de fora da Europa/América do Sul avançaram à fase final: EUA (1930), Cuba (1938), Coreia do Norte (1966) e México (1970).',
  'O Estádio Azteca, na Cidade do México, é o primeiro do mundo a receber três Copas: 1970, 1986 e 2026.',
  'O estádio com a maior altitude a já receber um jogo de Copa foi o Nemesio Díez, no México, a 2.670 metros de altitude.',
  'México, Brasil, França, Itália, Alemanha e Estados Unidos são os únicos países que já sediaram a Copa duas vezes (o México será o primeiro a sediar três, em 2026).',
  'A Copa de 2026 é a primeira da história com 48 seleções, divididas em 12 grupos de 4 times.',
  'Cabo Verde, Curaçao, Jordânia e Uzbequistão fazem sua primeira aparição em Copas do Mundo em 2026.',
  'O formato de 2026 criou uma nova fase eliminatória, chamada oficialmente de "Round of 32", antes das oitavas de final.',
  'Nenhum estádio foi construído especificamente para a Copa de 2026 — todos os 16 já existiam e foram adaptados.',
  'A Copa de 2026 é a primeira disputada por três países-sede ao mesmo tempo: Estados Unidos, México e Canadá.',
  'Em 1950, os Estados Unidos venceram a favorita Inglaterra por 1x0, resultado conhecido como "Milagre de Belo Horizonte".',
  'Em 1966, a Coreia do Norte venceu a Itália por 1x0 na fase de grupos e eliminou os italianos ainda na primeira fase.',
  'A seleção italiana, eliminada em 1966 pela Coreia do Norte, foi recebida com uma chuva de tomates e ovos por torcedores ao retornar à Itália.',
  'Em 1982, na sua estreia em Copas, a Argélia derrotou a Alemanha Ocidental por 2x1 — a primeira vitória de uma seleção africana sobre uma potência europeia em Mundiais.',
  'Em 1990, Camarões derrotou a Argentina de Maradona por 1x0 na abertura da Copa, mesmo terminando a partida com dois jogadores expulsos.',
  'A campanha de Camarões em 1990 (quartas de final) foi a melhor de uma seleção africana até então.',
  'Em 2002, o Senegal venceu a França, então campeã do mundo, por 1x0 na abertura do torneio — a França foi eliminada na fase de grupos sem marcar nenhum gol naquela Copa.',
  'Em 2022, a Arábia Saudita derrotou a Argentina de Messi por 2x1 — considerada a maior zebra estatística da história das Copas, com a Arábia tendo menos de 9% de chance de vitória antes do jogo.',
  'Em 1998, o Brasil, já classificado e atual campeão, perdeu para a Noruega por 2x1 na última rodada da fase de grupos.',
  'O Marrocos foi a primeira seleção africana e árabe a chegar a uma semifinal de Copa do Mundo, em 2022.',
  'O Marrocos sofreu apenas um gol em toda a Copa de 2022, e esse gol foi contra (marcado pelo próprio Aguerd).',
  'O goleiro marroquino Yassine Bounou ("Bono") defendeu dois pênaltis na disputa contra a Espanha, nas oitavas de 2022.',
  'Achraf Hakimi e Hakim Ziyech são os jogadores com mais partidas pelo Marrocos em Copas do Mundo.',
  'O Marrocos foi o primeiro país africano a disputar uma fase de grupos de Copa, em 1970.',
  'O Marrocos foi o primeiro país africano a se classificar para as oitavas de final, em 1986.',
  'O Egito foi a primeira seleção africana a disputar uma Copa do Mundo, em 1934 (na Itália).',
  'O Zaire (atual Congo) foi a primeira seleção da África subsaariana a participar de uma Copa, em 1974.',
  'A Tunísia foi a primeira seleção africana a vencer uma partida de Copa do Mundo.',
  'Antes de Marrocos, Camarões (1990), Senegal (2002) e Gana (2010) chegaram às quartas de final — melhor resultado africano até 2022.',
  'Pelé é o único jogador da história a ganhar a Copa do Mundo três vezes (1958, 1962, 1970).',
  'Pelé se tornou o jogador mais jovem a marcar em uma partida de Copa, aos 17 anos e 239 dias, em 1958.',
  'Na semifinal de 1958, Pelé se tornou o jogador mais jovem a marcar três gols em uma partida (hat-trick), com 17 anos e 8 meses.',
  'Pelé deu 6 assistências na Copa de 1970 — o maior número desde que essa estatística começou a ser contabilizada, em 1966.',
  'Pelé e Garrincha, jogando juntos pela seleção, nunca perderam uma partida entre 1958 e 1966 — 40 jogos, sendo 36 vitórias e 4 empates.',
  'Pelé e Garrincha estrearam e se despediram da seleção brasileira enfrentando o mesmo adversário: a Bulgária.',
  'Ronaldo Nazário é o maior artilheiro brasileiro em Copas do Mundo, com 15 gols.',
  'Ronaldo foi artilheiro da Copa de 2002, com 8 gols, incluindo os dois da final contra a Alemanha.',
  'Pelé tem a melhor média de gols por jogo entre os brasileiros em Copas: 0,86 gol por partida (12 gols em 14 jogos).',
  'Jairzinho marcou gol em todas as partidas do Brasil na Copa de 1970 — recorde único na história das Copas.',
  'Cafu é o único jogador a disputar três finais consecutivas de Copa: 1994, 1998 e 2002.',
  'Romário não entrou em campo na campanha do tetra de 1994, mas foi peça decisiva nas eliminatórias antes do torneio.',
  'Lionel Messi é o jogador com mais partidas disputadas na história das Copas do Mundo, com 26 jogos.',
  'O russo Oleg Salenko é o único jogador a marcar 5 gols em uma única partida de Copa (contra Camarões, em 1994).',
  'A Itália e o Brasil dividem o recorde de títulos consecutivos de Copa: Itália em 1934 e 1938, Brasil em 1958 e 1962.',
  'A Copa de 1958 foi a edição em que um único jogador (Just Fontaine) marcou mais gols: 13, em apenas 6 jogos.',
  'Achraf Hakimi, do Marrocos, marcou um pênalti decisivo de cavadinha (panenka) contra a Espanha em 2022 — ironicamente, ele nasceu na Espanha e passou pelas categorias de base do Real Madrid.',
  'A taça Jules Rimet, símbolo das primeiras Copas, foi roubada do Brasil em 1983 e nunca foi recuperada — acredita-se que tenha sido derretida e vendida como ouro.',
  'O que existe hoje no lugar da taça Jules Rimet original é uma réplica produzida pela própria FIFA, exposta no Museu do Futebol da CBF.',
  'A virada da Alemanha sobre a Hungria na final de 1954 ficou conhecida como o "Milagre de Berna".',
  'A Itália foi campeã em 1982 sob comando de Paolo Rossi, após o jogador ter cumprido suspensão por um escândalo de apostas no futebol italiano.',
  'A final de 2006 (Itália x França) é lembrada pela expulsão de Zinedine Zidane após uma cabeçada no zagueiro italiano Marco Materazzi.',
  'A Copa de 1994 foi decidida nos pênaltis entre Brasil e Itália — até hoje a única final de Copa decidida dessa forma.',
  'O confronto entre Argentina e Alemanha já decidiu três finais de Copa do Mundo: 1986, 1990 e 2014.',
  'O placar de 2x1 é o que mais apareceu na história das Copas, presente em todas as 23 edições já disputadas.',
  'O placar de 4x2 é o que mais se repetiu dentro de uma única edição: apareceu em 11 Copas diferentes.',
  'Os placares 4x3, 7x1 e 8x0 nunca se repetiram mais de uma vez na mesma edição de Copa.',
  'A Argentina de 2022 é o campeão mundial com o pior aproveitamento da história: 4 vitórias, 2 empates e 1 derrota (66,6%).',
  'A Croácia já disputou três quartas de final vencendo todas elas: 1998, 2018 e 2022.',
  'A Irlanda tem o melhor desempenho histórico de uma seleção eliminada nas quartas de final sem vencer nenhuma partida: 4 empates e 1 derrota, em 1990.',
  'A Copa de 2018, na Rússia, teve a eliminação mais inédita nas quartas de final: a própria seleção anfitriã.',
  'Em 2014, a eliminação da Argélia e da Grécia ainda nas oitavas de final marcou a estreia desses países nessa fase do torneio.',
  'A Bélgica terminou em 3º lugar em 2018 — seu melhor resultado histórico em Copas do Mundo até então.',
  'A Copa de 2022 teve sete jogos terminando 0x0 — empatando o recorde histórico de mais empates sem gols numa edição.',
  'Cabo Verde, Curaçao, Jordânia e Uzbequistão disputam sua primeira Copa do Mundo em 2026.',
  'O goleiro de Cabo Verde, Vozinha, foi destaque ao defender chances claras no empate 0x0 contra a Espanha em 2026.',
  'Curaçao é, até o momento, uma das menores nações (em população) a disputar uma Copa do Mundo.',
  'Mário Zagallo tem quatro títulos de Copa do Mundo no currículo: dois como jogador (1958, 1962), um como técnico (1970) e um como auxiliar (1994).',
  'A Argentina é a atual campeã mundial, tendo vencido a Copa de 2022 sob comando de Lionel Scaloni.',
  'O técnico português Walid Regragui assumiu o Marrocos pouco antes da Copa de 2022 e o levou à histórica semifinal.',
  'A Copa do Mundo é disputada a cada 4 anos desde 1930, com exceção de 1942 e 1946, quando não houve torneio por causa da Segunda Guerra Mundial.',
  'Apenas duas Copas tiveram menos de 16 seleções participantes: 1930 (13) e 1950 (13).',
  'A Copa de 1934, na Itália, foi usada pelo regime fascista de Mussolini como ferramenta de propaganda política.',
  'O primeiro gol da história das Copas do Mundo foi marcado pelo francês Lucien Laurent, em 1930.',
  'A primeira Copa disputada fora da Europa e da América do Sul foi a de 2002, no Japão e Coreia do Sul.',
  'A Copa de 2002 também foi a primeira disputada conjuntamente por dois países-sede diferentes.',
  'O torneio que viria a se tornar a Copa do Mundo foi idealizado pelo francês Jules Rimet, então presidente da FIFA.',
  'A primeira Copa, em 1930, teve o campeão sendo também o país-sede: o Uruguai.',
  'O Brasil foi sede de Copa do Mundo duas vezes: em 1950 e em 2014, vivendo momentos dolorosos em ambas.',
  'Em 2014, o Brasil sofreu uma das maiores goleadas da história das semifinais de Copa: 7x1 para a Alemanha.',
  'O "Maracanazo" de 1950 — derrota do Brasil para o Uruguai na final, em pleno Maracanã — é considerado um dos maiores traumas do futebol brasileiro.',
  'O Brasil precisava apenas de um empate contra o Uruguai na decisão de 1950 para ser campeão, e perdeu por 2x1.',
  'A seleção da Escócia disputou 8 Copas do Mundo e nunca avançou da fase de grupos em nenhuma delas.',
  'A seleção do Brasil tem a maior pontuação relativa histórica (vitórias por jogos disputados) entre todas as seleções que já disputaram Copas.',
  'A Hungria de 1954, apesar de ter goleado seus adversários na fase de grupos (9x0 e 8x3), perdeu a final para a Alemanha Ocidental no "Milagre de Berna".',
  'A União Soviética venceu todos os jogos da fase de grupos da Copa de 1966, mas foi eliminada na semifinal.',
  'As substituições de jogadores durante uma partida só começaram a ser permitidas em Copas a partir da década de 1950, e só em caso de lesão.',
  'Os números nas camisas dos jogadores em Copas do Mundo só foram introduzidos a partir da edição de 1950.',
  'A Copa de 1998 foi a primeira a usar a regra do "Gol de Ouro" na prorrogação — decisão automática pelo primeiro gol marcado.',
  'A regra do Gol de Ouro foi usada apenas nas Copas de 1998 e 2002, sendo abolida depois.',
  'O primeiro mascote oficial da história das Copas foi Willie, um leão cartunesco, na Copa de 1966, na Inglaterra.',
  'O mascote da Copa de 1974, na Alemanha, foi a dupla Tip e Tap — o primeiro mascote duplo da história das Copas.',
  'O mascote da Copa de 1978, na Argentina, se chamava Gauchito, em referência aos gaúchos da América Latina.',
  'O mascote da Copa de 1982, na Espanha, foi Naranjito, uma laranja sorridente representando uma fruta típica do país.',
  'O mascote da Copa de 1986, no México, foi Pique, uma pimenta jalapeño com sombrero.',
  'O mascote da Copa de 1990, na Itália, foi Ciao — uma figura geométrica formada por blocos coloridos, sem rosto, com uma bola no lugar da cabeça.',
  'O mascote da Copa de 1994, nos EUA, foi escolhido por votação popular: Striker, um cachorro com uniforme das cores da bandeira americana.',
  'O mascote da Copa de 1998, na França, foi Footix, um galo — nome que combina "football" com "Asterix".',
  'A Copa de 2002 teve os primeiros três mascotes da história: Ato, Kaz e Nik, criaturas futuristas que praticavam um esporte fictício chamado "Atmoball".',
  'O mascote da Copa de 2006, na Alemanha, foi Goleo VI, um leão de pelúcia acompanhado de uma bola falante chamada Pille.',
  'O mascote da Copa de 2014, no Brasil, foi Fuleco, um tatu-bola — espécie nativa brasileira ameaçada de extinção. O nome combina "futebol" e "ecologia".',
  'O mascote da Copa de 2018, na Rússia, foi Zabivaka, um lobo escolhido por votação popular — seu nome significa algo como "aquele que marca gols".',
  'O mascote da Copa de 2022, no Catar, foi La\'eeb, inspirado em um lenço tradicional árabe — seu nome significa "jogador habilidoso".',
  'A Copa de 2026 tem três mascotes inéditos, um para cada país-sede: Maple (alce, Canadá), Zayu (onça-pintada, México) e Clutch (águia, Estados Unidos).',
  'O nome do mascote mexicano de 2026, Zayu, vem do náuatle e significa "jovem".',
  'O mascote canadense de 2026, Maple, tem nome inspirado na árvore bordo (maple), símbolo do Canadá.',
  'A bola da primeira Copa, em 1930, tinha 11 tiras de couro costuradas à mão em formato de "T".',
  'A final de 1930, entre Uruguai e Argentina, foi disputada com duas bolas diferentes — uma escolhida por cada seleção para cada tempo de jogo.',
  'A bola da Copa de 1970, a Telstar, foi a primeira com o icônico padrão de gomos pretos e brancos, hoje símbolo universal de bola de futebol.',
  'A Tricolore, bola da Copa de 1998 na França, foi a primeira bola multicolorida da história das Copas, homenageando a bandeira francesa.',
  'A Brazuca, bola oficial da Copa de 2014, foi a primeira bola de Copa sem cadarços aparentes.',
  'A Al Rihla, bola da Copa de 2022, foi descrita pela Adidas como a bola mais rápida da história das Copas do Mundo.',
  'A bola de 2022 (Al Rihla) foi a primeira a usar tecnologia "Connected Ball", capaz de auxiliar decisões de arbitragem em tempo real.',
  'A bola Telstar 18, usada em 2018, incorporava um chip NFC que permitia interação com smartphones.',
  'Antes de 1970, as bolas das Copas eram inteiramente de couro natural, o que fazia com que absorvessem água e ficassem mais pesadas em jogos chuvosos.',
  'A bola usada na final entre Inglaterra e Alemanha Ocidental, em 1966, ficou eternizada por sua versão na cor laranja, mais visível em campo.',
  'A Copa de 1974, na Alemanha, foi disputada num contexto histórico especial: o país ainda estava dividido entre Alemanha Oriental e Ocidental.',
  'Apenas 8 países já foram campeões da Copa do Mundo: Brasil, Alemanha, Itália, Argentina, França, Uruguai, Inglaterra e Espanha.',
  'Todos os campeões de Copa do Mundo até hoje são da Europa ou da América do Sul — nenhuma seleção de outro continente já venceu o torneio.',
  'A Europa soma 12 títulos de Copa do Mundo; a América do Sul soma 10.',
  'O Brasil é o único país a vencer Copas em outro continente: na Europa (1958) e na Ásia (2002).',
  'A Espanha (2010), a Alemanha (2014) e a Argentina (2022) são os únicos campeões a vencerem fora de seu próprio continente, além do Brasil.',
  'Seis seleções já foram campeãs jogando em casa: Uruguai (1930), Itália (1934), Inglaterra (1966), Alemanha (1974), Argentina (1978) e França (1998).',
  'O Brasil e a Itália são os únicos países que já venceram duas Copas consecutivas: Brasil em 1958/1962, Itália em 1934/1938.',
  'A Inglaterra venceu sua única Copa em 1966, jogando em casa, derrotando a Alemanha Ocidental por 4x2 na final.',
  'A Espanha venceu sua única Copa em 2010, na África do Sul — o único título de sua história.',
  'A Alemanha tem 4 títulos: 1954, 1974, 1990 e 2014.',
  'O título alemão de 1954 ficou conhecido como o "Milagre de Berna", quando a seleção derrotou a favorita Hungria na final.',
  'Mbappé (2022) e Geoff Hurst (1966) são os únicos jogadores que marcaram três gols (hat-trick) em uma final de Copa do Mundo — feito separado por 56 anos.',
  'A Argentina é a atual campeã mundial, com o título conquistado em 2022, no Catar, vencendo a França nos pênaltis.',
  'França (1998), Itália (2006) e Espanha (2010) tiveram o melhor desempenho defensivo de uma seleção campeã, sofrendo apenas dois gols em toda a competição.',
  'A Suíça tem o melhor desempenho defensivo isolado de uma edição: eliminada nas oitavas de 2006 sem sofrer nenhum gol, perdendo apenas nos pênaltis.',
  'A Alemanha de 1954 marcou 25 gols ao longo da Copa — o melhor desempenho ofensivo de uma seleção campeã da história.',
  'A Hungria, na mesma Copa de 1954, estabeleceu o recorde de mais gols marcados por uma seleção em uma única edição: 27 gols.',
  'O recorde de gols marcados em uma única partida de Copa do Mundo é de 1954: Áustria 7x5 Suíça, totalizando 12 gols.',
  'A Alemanha é a seleção que mais vezes disputou finais de Copa do Mundo: 8 vezes.',
  'O Brasil é o segundo país com mais finais disputadas: 7 vezes.',
  'A final de 2014 (Alemanha 1x0 Argentina) foi decidida com gol de Mario Götze na prorrogação, disputada no Maracanã.',
  'Até hoje, a única final de Copa decidida nos pênaltis envolvendo o Brasil foi contra a Itália, em 1994.',
  'Até 1970, o troféu entregue ao campeão se chamava Taça Jules Rimet; o nome mudou para "Troféu da Copa do Mundo" em 1974.',
  'A mudança de nome do troféu aconteceu porque o Brasil, ao se tornar tricampeão em 1970, ficou em definitivo com a Taça Jules Rimet original.',
  'Brasil e Argentina já se enfrentaram três vezes na segunda fase/mata-mata de Copas, em 1974, 1978 e 1982 — o confronto mais repetido nessa fase.',
  'Brasil e Chile já se enfrentaram três vezes nas oitavas de final de Copas: 1998, 2010 e 2014.',
  'O confronto Alemanha x Iugoslávia/Sérvia já decidiu três quartas de final diferentes: 1954, 1958 e 1962.',
  'Cinco países já sediaram a Copa do Mundo duas vezes: Itália, França, México, Alemanha e Brasil.',
  'Com a Copa de 2026, o México se torna o primeiro país a sediar três edições do torneio: 1970, 1986 e 2026.',
  'A tecnologia de impedimento semiautomático foi usada por completo pela primeira vez na Copa de 2022, com 12 câmeras rastreando até 29 pontos do corpo de cada jogador, 50 vezes por segundo.',
  'Desde a Copa de 2022, a bola oficial passou a contar com um sensor interno capaz de determinar o exato momento do toque de um jogador.',
  'Em 1970, a Copa do Mundo foi transmitida por TV em cores para o público pela primeira vez na história.',
  'A primeira transmissão em cores da Copa, em 1970, gerou uma corrida às lojas de eletrônicos em muitos países, incluindo o Brasil.',
  'Desde a reunificação alemã, em 1990, os jogadores de Copa também passaram a usar numeração nos calções, além das camisas.',
  'A Copa do Mundo de 2026, com 48 seleções e 104 jogos, é a maior edição da história em número de partidas e países participantes.',
];
